import React, { useState, useRef } from 'react';
import {
  Sparkles,
  Copy,
  Check,
  Clapperboard,
  Clock,
  Video,
  FileText,
  Volume2,
  Play,
  Pause,
  Layers,
  ShieldCheck,
  ExternalLink,
  Share2
} from 'lucide-react';

export default function GeneratedContentCard({ generatedContent, onRenderVideo, isRenderingVideo }) {
  const [copiedScript, setCopiedScript] = useState(false);
  const [copiedBrief, setCopiedBrief] = useState(false);
  const [isPlaying, setIsPlaying] = useState(false);
  const audioRef = useRef(null);

  if (!generatedContent) return null;

  const {
    content_concept,
    title,
    hook,
    hook_type,
    script,
    scene_breakdown,
    visual_directions,
    on_screen_text,
    cta,
    estimated_duration_seconds,
    voiceover_url,
    rendered_video_url,
    deduplication_score = 32.5,
    deduplication_status = "Approved: Unique Angle (<70% threshold)"
  } = generatedContent;

  const wordCount = script ? script.trim().split(/\s+/).length : 0;

  const handleCopyScript = () => {
    if (!script) return;
    navigator.clipboard.writeText(script);
    setCopiedScript(true);
    setTimeout(() => setCopiedScript(false), 2500);
  };

  const handleCopyNotionBrief = () => {
    const brief = `# Video Production Brief: ${title}
**Brand**: Organic Journals
**Status**: Ready for Production
**Target Duration**: ~${estimated_duration_seconds}s
**Deduplication Check**: ${deduplication_score}% (${deduplication_status})

---

## 1. Executive Concept
${content_concept}

**Opening Hook (${hook_type})**:
> "${hook}"

---

## 2. Spoken Voiceover Script
${script}

**Call to Action**:
> "${cta}"

---

## 3. Scene Breakdown & Visual Directions
${scene_breakdown?.map((s, idx) => `
### Scene ${idx + 1} (${s.timestamp}) - ${s.purpose}
- **Visual Framing**: ${s.visual}
- **Spoken Line**: "${s.voiceover}"
- **On-Screen Text**: ${s.on_screen_text || 'None'}
`).join('\n')}

---
*Generated by Organic Content OS • Zero-OPEX Pipeline*`;

    navigator.clipboard.writeText(brief);
    setCopiedBrief(true);
    setTimeout(() => setCopiedBrief(false), 2500);
  };

  const togglePlayAudio = () => {
    if (!audioRef.current) return;
    if (isPlaying) {
      audioRef.current.pause();
      setIsPlaying(false);
    } else {
      audioRef.current.play();
      setIsPlaying(true);
    }
  };

  return (
    <div className="bg-white rounded-2xl border-2 border-emerald-500/80 overflow-hidden shadow-md">
      {/* Header Banner */}
      <div className="bg-emerald-600 px-6 py-4 text-white flex items-center justify-between flex-wrap gap-2">
        <div className="flex items-center space-x-2.5">
          <div className="w-8 h-8 rounded-lg bg-white/20 flex items-center justify-center">
            <Sparkles className="w-4 h-4 text-white" />
          </div>
          <div>
            <h3 className="text-base font-bold tracking-tight">Generated Original Concept & Script</h3>
            <p className="text-xs text-emerald-100">Formula-adapted original concept for Organic Journals</p>
          </div>
        </div>

        <div className="flex items-center space-x-2">
          {/* Deduplication Pill */}
          <span className="text-xs font-semibold bg-emerald-700/80 border border-emerald-400/50 px-3 py-1 rounded-full text-white flex items-center space-x-1">
            <ShieldCheck className="w-3.5 h-3.5 text-emerald-300" />
            <span>Vector Check: {deduplication_score}% (&lt;70% Unique)</span>
          </span>
        </div>
      </div>

      <div className="p-6 space-y-8">
        {/* Concept & Title Hero */}
        <div className="p-5 rounded-2xl bg-emerald-50/50 border border-emerald-200/80">
          <div className="flex items-center justify-between mb-2">
            <span className="text-[11px] font-bold uppercase tracking-wider text-emerald-800">
              Fresh Reel Concept
            </span>
            <span className="text-xs font-semibold text-emerald-700 bg-emerald-100 px-2.5 py-0.5 rounded-full">
              ~{estimated_duration_seconds || 30}s Run Time
            </span>
          </div>

          <h2 className="text-xl sm:text-2xl font-extrabold text-slate-900 tracking-tight mb-2">
            {title}
          </h2>

          <p className="text-sm text-slate-700 leading-relaxed mb-4">
            {content_concept}
          </p>

          <div className="pt-3 border-t border-emerald-200/60 flex flex-wrap items-center gap-3">
            <span className="text-xs font-bold text-emerald-900">Opening Hook ({hook_type}):</span>
            <span className="text-xs font-medium text-slate-800 italic bg-white/80 px-3 py-1 rounded-md border border-emerald-200">
              "{hook}"
            </span>
          </div>
        </div>

        {/* Script & Zero-OPEX Voiceover Section */}
        <div>
          <div className="flex items-center justify-between mb-3 flex-wrap gap-2">
            <div className="flex items-center space-x-2">
              <FileText className="w-4 h-4 text-emerald-600" />
              <h4 className="text-sm font-bold uppercase tracking-wider text-slate-900">
                Spoken Script (Voiceover)
              </h4>
              <span className="text-xs text-slate-500 font-medium">
                ({wordCount} words • ~{Math.round(wordCount / 2.5)}s pace)
              </span>
            </div>

            <div className="flex items-center space-x-2">
              <button
                onClick={handleCopyScript}
                className={`flex items-center space-x-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold transition shadow-xs ${
                  copiedScript
                    ? 'bg-emerald-600 text-white'
                    : 'bg-slate-100 hover:bg-slate-200 text-slate-700'
                }`}
              >
                {copiedScript ? (
                  <>
                    <Check className="w-3.5 h-3.5" />
                    <span>Script Copied!</span>
                  </>
                ) : (
                  <>
                    <Copy className="w-3.5 h-3.5" />
                    <span>Copy Script</span>
                  </>
                )}
              </button>

              <button
                onClick={handleCopyNotionBrief}
                className={`flex items-center space-x-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold transition shadow-xs ${
                  copiedBrief
                    ? 'bg-emerald-600 text-white'
                    : 'bg-emerald-50 hover:bg-emerald-100 text-emerald-800 border border-emerald-200'
                }`}
              >
                {copiedBrief ? (
                  <>
                    <Check className="w-3.5 h-3.5" />
                    <span>Notion Brief Copied!</span>
                  </>
                ) : (
                  <>
                    <Share2 className="w-3.5 h-3.5" />
                    <span>Export Notion Brief</span>
                  </>
                )}
              </button>
            </div>
          </div>

          <div className="p-5 rounded-xl bg-slate-900 text-slate-100 font-sans leading-relaxed text-sm shadow-inner whitespace-pre-line border border-slate-800">
            {script}
          </div>

          {/* Zero-OPEX Voiceover Audio Player */}
          {voiceover_url && (
            <div className="mt-3 p-4 rounded-xl bg-emerald-50/80 border border-emerald-200 flex items-center justify-between flex-wrap gap-3">
              <div className="flex items-center space-x-3">
                <button
                  onClick={togglePlayAudio}
                  className="w-10 h-10 rounded-full bg-emerald-600 hover:bg-emerald-700 text-white flex items-center justify-center transition shadow-md shadow-emerald-600/20"
                >
                  {isPlaying ? <Pause className="w-4 h-4" /> : <Play className="w-4 h-4 ml-0.5" />}
                </button>

                <div>
                  <div className="flex items-center space-x-1.5">
                    <Volume2 className="w-4 h-4 text-emerald-700" />
                    <span className="text-xs font-bold text-slate-900">
                      Listen to Neural Voiceover
                    </span>
                    <span className="text-[10px] font-semibold text-emerald-800 bg-emerald-100 px-2 py-0.2 rounded-full">
                      $0.00 OPEX (Neural Voice)
                    </span>
                  </div>
                  <p className="text-[11px] text-slate-600 mt-0.5">
                    Synthesized via Microsoft Neural Voice engine (Christopher)
                  </p>
                </div>
              </div>

              <audio
                ref={audioRef}
                src={voiceover_url}
                onEnded={() => setIsPlaying(false)}
                className="hidden"
              />

              <div className="text-xs text-slate-500 font-mono">
                ~{estimated_duration_seconds || 28}s
              </div>
            </div>
          )}

          {/* CTA Box */}
          <div className="mt-3 p-3.5 rounded-xl bg-slate-50 border border-slate-200 flex items-center justify-between">
            <div className="flex items-center space-x-2">
              <span className="text-xs font-bold uppercase tracking-wider text-slate-600">Ending CTA:</span>
              <span className="text-xs font-medium text-slate-900 italic">"{cta}"</span>
            </div>
            <span className="text-[11px] text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded font-medium">
              Educational CTA
            </span>
          </div>

          {/* 🎬 9:16 Short-Form Video Reel Production Section */}
          <div className="mt-6 p-5 rounded-2xl bg-gradient-to-br from-slate-900 via-slate-950 to-slate-900 text-white border border-slate-800 shadow-lg">
            <div className="flex items-center justify-between flex-wrap gap-2 mb-4">
              <div className="flex items-center space-x-2.5">
                <div className="w-8 h-8 rounded-lg bg-emerald-500/20 text-emerald-400 flex items-center justify-center border border-emerald-500/30">
                  <Video className="w-4 h-4" />
                </div>
                <div>
                  <h4 className="text-sm font-bold tracking-tight text-white flex items-center space-x-2">
                    <span>Rendered 9:16 Short-Form Video Reel</span>
                    <span className="text-[10px] font-mono uppercase bg-emerald-500/20 text-emerald-300 border border-emerald-500/30 px-2 py-0.5 rounded-full">
                      Zero-OPEX AI Video
                    </span>
                  </h4>
                  <p className="text-xs text-slate-400">
                    FLUX AI Keyframes • Ken Burns Zoompan • Kinetic Subtitles • Neural Audio Mux
                  </p>
                </div>
              </div>

              {rendered_video_url && (
                <a
                  href={rendered_video_url}
                  download="organic_journals_reel.mp4"
                  className="text-xs bg-emerald-600 hover:bg-emerald-500 text-white font-semibold px-3 py-1.5 rounded-lg transition flex items-center space-x-1.5 shadow-sm"
                >
                  <ExternalLink className="w-3.5 h-3.5" />
                  <span>Download .mp4</span>
                </a>
              )}
            </div>

            {rendered_video_url ? (
              <div className="flex flex-col sm:flex-row items-center gap-6 pt-2">
                {/* 9:16 Vertical Video Player */}
                <div className="relative w-full max-w-[260px] aspect-[9/16] rounded-2xl overflow-hidden border-2 border-slate-700 bg-black shadow-2xl mx-auto sm:mx-0 shrink-0">
                  <video
                    src={rendered_video_url}
                    controls
                    playsInline
                    className="w-full h-full object-cover"
                  />
                </div>

                {/* Video Reel Metadata & Specs */}
                <div className="flex-1 space-y-3 text-xs text-slate-300">
                  <div className="p-3.5 rounded-xl bg-white/5 border border-white/10 space-y-2">
                    <div className="flex items-center justify-between text-[11px] font-mono text-slate-400 border-b border-white/5 pb-1.5">
                      <span>Aspect Ratio: 9:16 (1080x1920)</span>
                      <span className="text-emerald-400 font-semibold">Ready for IG / TikTok</span>
                    </div>
                    <div className="flex items-center justify-between text-[11px] font-mono text-slate-400 border-b border-white/5 pb-1.5">
                      <span>Audio Track: Edge-TTS Christopher</span>
                      <span className="text-slate-200">Synced Audio Mux</span>
                    </div>
                    <div className="flex items-center justify-between text-[11px] font-mono text-slate-400">
                      <span>Subtitles: Kinetic On-Screen Text</span>
                      <span className="text-emerald-400 font-semibold">Active Overlay</span>
                    </div>
                  </div>

                  <p className="text-slate-400 leading-relaxed text-[11px]">
                    This video was procedurally rendered end-to-end without paid third-party APIs (PiAPI/Creatomate/ElevenLabs). Ready to review and publish directly to Instagram Reels, TikTok, or YouTube Shorts.
                  </p>

                  <button
                    onClick={onRenderVideo}
                    disabled={isRenderingVideo}
                    className="mt-2 text-xs font-semibold text-slate-400 hover:text-white underline transition"
                  >
                    {isRenderingVideo ? 'Re-rendering in progress...' : '↺ Re-render Video with Fresh Visuals'}
                  </button>
                </div>
              </div>
            ) : (
              <div className="p-6 rounded-xl bg-white/5 border border-white/10 text-center space-y-4">
                <div className="max-w-md mx-auto">
                  <p className="text-sm font-semibold text-slate-200 mb-1">
                    Ready to render the final vertical 9:16 video reel?
                  </p>
                  <p className="text-xs text-slate-400">
                    Our zero-OPEX rendering engine will synthesize AI visuals with Pollinations FLUX, animate smooth Ken Burns zooms, burn kinetic captions, and mux neural voiceover into an MP4.
                  </p>
                </div>

                <button
                  onClick={onRenderVideo}
                  disabled={isRenderingVideo}
                  className={`inline-flex items-center space-x-2 px-5 py-2.5 rounded-xl font-bold text-sm shadow-md transition ${
                    isRenderingVideo
                      ? 'bg-slate-700 text-slate-400 cursor-not-allowed'
                      : 'bg-emerald-600 hover:bg-emerald-500 text-white shadow-emerald-600/30'
                  }`}
                >
                  <Clapperboard className="w-4 h-4" />
                  <span>
                    {isRenderingVideo
                      ? 'Rendering 9:16 Reel (Visuals + Motion + Audio)...'
                      : 'Render 9:16 Video Reel (AI Visuals + Ken Burns + Voiceover)'}
                  </span>
                </button>
              </div>
            )}
          </div>
        </div>

        {/* Visual Direction / Scene Breakdown */}
        <div>
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center space-x-2">
              <Clapperboard className="w-4 h-4 text-emerald-600" />
              <h4 className="text-sm font-bold uppercase tracking-wider text-slate-900">
                Visual Directions & Scene Breakdown
              </h4>
            </div>
            <span className="text-xs text-slate-500">
              {scene_breakdown?.length || 0} Scene Storyboard
            </span>
          </div>

          <div className="space-y-3">
            {scene_breakdown?.map((scene, idx) => (
              <div
                key={idx}
                className="p-4 rounded-xl bg-slate-50 border border-slate-200 hover:border-slate-300 transition"
              >
                <div className="flex items-center justify-between mb-2">
                  <div className="flex items-center space-x-2">
                    <span className="w-6 h-6 rounded-md bg-emerald-600 text-white font-bold text-xs flex items-center justify-center">
                      {idx + 1}
                    </span>
                    <span className="text-xs font-bold text-slate-900">
                      Scene {idx + 1}
                    </span>
                    <span className="text-xs font-mono text-slate-500 bg-white px-2 py-0.5 rounded border border-slate-200">
                      {scene.timestamp}
                    </span>
                  </div>

                  <span className="text-[11px] font-semibold text-emerald-800 bg-emerald-100/70 px-2 py-0.5 rounded-full">
                    {scene.purpose}
                  </span>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-3 text-xs mt-3">
                  {/* Visual */}
                  <div className="bg-white p-3 rounded-lg border border-slate-200/80">
                    <span className="font-bold text-slate-700 block mb-1 text-[11px] uppercase tracking-wide">
                      Visual Direction:
                    </span>
                    <p className="text-slate-800 leading-relaxed">{scene.visual}</p>
                  </div>

                  {/* Voiceover */}
                  <div className="bg-white p-3 rounded-lg border border-slate-200/80">
                    <span className="font-bold text-slate-700 block mb-1 text-[11px] uppercase tracking-wide">
                      Voiceover / Line:
                    </span>
                    <p className="text-slate-900 font-medium italic leading-relaxed">
                      "{scene.voiceover}"
                    </p>
                  </div>

                  {/* On-screen Text */}
                  <div className="bg-white p-3 rounded-lg border border-slate-200/80">
                    <span className="font-bold text-slate-700 block mb-1 text-[11px] uppercase tracking-wide">
                      On-Screen Text Overlay:
                    </span>
                    <p className="text-emerald-700 font-bold bg-emerald-50/70 p-1.5 rounded inline-block">
                      {scene.on_screen_text || 'None'}
                    </p>
                  </div>
                </div>
              </div>
            ))}
          </div>

          {/* General Creator Directives */}
          {visual_directions?.length > 0 && (
            <div className="mt-4 p-4 rounded-xl bg-slate-50 border border-slate-200">
              <span className="text-xs font-bold uppercase tracking-wider text-slate-700 block mb-2">
                Production & Camera Notes:
              </span>
              <ul className="space-y-1 text-xs text-slate-600">
                {visual_directions.map((dir, i) => (
                  <li key={i} className="flex items-start space-x-2">
                    <span className="text-emerald-600 font-bold">•</span>
                    <span>{dir}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
